spring:
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
        # 命名空间
        namespace: d30d8ecb-9dd4-4c56-8a4e-8cc2194158ff
        #用户名，密码
        username: nacos
        password: nacos123456.
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        namespace: d30d8ecb-9dd4-4c56-8a4e-8cc2194158ff
        #用户名，密码
        username: nacos
        password: nacos123456.
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8718