apiVersion: v1
kind: Namespace
metadata:
  name: nacos-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: nacos-namespace
spec:
  selector:
    app: nacos
  type: NodePort
  ports:
  - name: http
    port: 8848
    targetPort: 8848
    nodePort: 30001
  - name: client-rpc
    port: 9848
    targetPort: 9848
    nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: nacos-namespace
  labels:
    app: nacos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.4.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8848
        - name: cluster
          containerPort: 8849
        - name: client-rpc
          containerPort: 9848
        - name: raft-rpc
          containerPort: 9849
        env:
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: nacos.mode
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: mysql.host
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: mysql.port
        - name: MYSQL_SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: mysql.db.name
        - name: MYSQL_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: mysql.user
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: nacos-config
              key: mysql.password
        - name: NACOS_AUTH_ENABLE
          valueFrom:
            configMapKeyRef:
              key: nacos.auth.enable
              name: nacos-config
        - name: NACOS_AUTH_CACHE_ENABLE
          valueFrom:
            configMapKeyRef:
              key: nacos.auth.cache.enable
              name: nacos-config
        - name: NACOS_AUTH_TOKEN
          valueFrom:
            configMapKeyRef:
              key: nacos.auth.token
              name: nacos-config
        - name: NACOS_AUTH_IDENTITY_KEY
          valueFrom:
            configMapKeyRef:
              key: nacos.auth.identity.key
              name: nacos-config
        - name: NACOS_AUTH_IDENTITY_VALUE
          valueFrom:
            configMapKeyRef:
              key: nacos.auth.identity.value
              name: nacos-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: nacos-namespace
data:
  nacos.mode: "cluster"
  mysql.db.name: ry-config
  mysql.host: 120.25.106.163
  mysql.password: lsy19980104
  mysql.port: "3306"
  mysql.user: myconnect
  nacos.auth.enable: "true"
  nacos.auth.cache.enable: "true"
  nacos.auth.token: "VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzl="
  nacos.auth.identity.key: "nacos"
  nacos.auth.identity.value: "nacos123456."