version : '3.8'
services:
  ruoyi-gateway:
    image: ruoyi-gateway:1.3
    container_name: ruoyi-gateway
    build:
      context: ./ruoyi/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
